export const PROVIDER_ID_ALIASES: Record<string, string> = {
  'azure-openai': 'azureai',
  'new-api': 'newapi',
  'tencent-cloud-ti': 'tencentCloudTi',
  'baidu-cloud': 'baiduCloud',
  'aws-bedrock': 'awsBedrock',
  'gitee-ai': 'giteeAi',
  yi: 'zeroOne',
  ovms: 'intel',
  gemini: 'google',
  copilot: 'githubCopilot',
  doubao: 'volcengine',
  stepfun: 'step',
  voyageai: 'voyage',
  gateway: 'vercel',
  zhinao: 'xirang',
  aionly: 'aiOnly',
  dashscope: 'bailian',
  zai: 'zAi',
  'minimax-global': 'minimax',
  cherryai: 'cherryin',
};
